"""add_password_reset_columns

Revision ID: b90057c093eb
Revises: f1d36396318b
Create Date: 2026-07-02 11:27:30.891920

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b90057c093eb"
down_revision: str | None = "f1d36396318b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("last_password_changed", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("password_reset_token", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("password_reset_expires_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_reset_expires_at")
    op.drop_column("users", "password_reset_token")
    op.drop_column("users", "last_password_changed")
    # ### end Alembic commands ###
